INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)VALUES(100, 'SALARY', 'EUR', 'Maniek', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)VALUES(500, 'ADHOC_WORK', 'EUR', 'Maniek', CURRENT_TIMESTAMP);

INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)VALUES(170, 'RENT', 'EUR', 'Maniek', CURRENT_TIMESTAMP);
INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)VALUES(190, 'GOVERNMENT_SUPPORT', 'EUR', 'Maniek', CURRENT_TIMESTAMP);
INSERT INTO INCOMES(AMOUNT, CATEGORY, CURRENCY, PERSON, TIMESTAMP)VALUES(400, 'GIFT', 'EUR', 'Maniek', CURRENT_TIMESTAMP);